

export const FURNITURE = [
    {
        "id": 1,
        "title": "Adolph 8 Seater Dining Table Set (Walnut Finish)",
        "price": 59389,
        "mrp": 70000, 
        "offerPercentage": 15,
        "description": "Elegant 8-seater dining table set with a walnut finish, perfect for large dining spaces.",
        "category": "dining table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1657271967/crusader/variants/PB-DR0109/Seb-Dining-Squaie-Table-Set8__1_-1657271965.jpg",
        "rating": {
            "rate": 4.2,
            "count": 10
        },
        "brand": "Urban Ladder",
        "colour": "Brown",
        "material": "Sheesham Wood",
        "productDimensions": "200D x 100W x 76H cm",
        "size": "8 Seater",
        "backStyle": "None",
        "specialFeature": "High durability, Water-resistant finish",
        "productCareInstructions": "Wipe with a dry cloth. Avoid using abrasive cleaners.",
        "netQuantity": "1 Set",
        "seatMaterialType": "Wood"
    },
    {
        "id": 2,
        "title": "Adolph Compact 4 Seater Dining Table Set with Bench (Walnut Finish)",
        "price": 29599,
        "mrp": 35000, 
        "offerPercentage": 15,
        "description": "Compact 4-seater dining set with a bench and walnut finish, ideal for smaller dining areas.",
        "category": "dining table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1632911401/crusader/variants/PB-DR0030/Theo-Round-Dining-Table-With-4-Joshua-Chairs-Meadow-Yellow.jpg",
        "rating": {
            "rate": 4.5,
            "count": 242
        },
        "brand": "Home Centre",
        "colour": "Walnut",
        "material": "Mango Wood",
        "productDimensions": "150D x 90W x 75H cm",
        "size": "4 Seater",
        "backStyle": "Slat Back",
        "specialFeature": "Bench seating for added space, Contemporary design",
        "productCareInstructions": "Use coasters or mats to prevent scratches. Avoid direct sunlight.",
        "netQuantity": "1 Set",
        "seatMaterialType": "Wood"
    },
    {
        "id": 3,
        "title": "Adolph Compact Wooden Dining Table Set 4 Seater (Walnut Finish)",
        "price": 32699,
        "mrp": 40000,
        "offerPercentage": 18,
        "description": "Wooden 4-seater dining table set with a walnut finish, adorable and stylish and durable.",
        "category": "dining table",
        "image": "https://images.woodenstreet.de/image/cache/data%2Fdining-set%2F6-seater%2Fvalence%2F16-750x650.jpg",
        "rating": {
            "rate": 4.0,
            "count": 251
        },
        "brand": "Pepperfry",
        "colour": "Dark Brown",
        "material": "Engineered Wood",
        "productDimensions": "140D x 80W x 74H cm",
        "size": "4 Seater",
        "backStyle": "Ladder Back",
        "specialFeature": "Scratch-resistant, Easy assembly",
        "productCareInstructions": "Clean with a soft, dry cloth. Do not use water or solvents.",
        "netQuantity": "1 Set",
        "seatMaterialType": "Wood"
    },
    {
        "id": 4,
        "title": "Feltro Sheesham Wood Sofa With Storage (King Size, Honey Irish Cream)",
        "price": 36499,
        "mrp": 45000,
        "offerPercentage": 19,
        "description": "King size Sheesham wood sofa bed with storage in honey Irish cream, versatile and space-saving.",
        "category": "sofa bed",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1692703128/crusader/variants/PB-000617-TL4002-WA/Owen-3-Seater-Sofa-With-Armchair-With-Ottoman-Pearl_Beige-Natrual-Square-Set_4-1692703125.jpg",
        "rating": {
            "rate": 4.8,
            "count": 1154
        },
        "brand": "IKEA",
        "colour": "Honey Irish Cream",
        "material": "Sheesham Wood",
        "productDimensions": "200D x 150W x 90H cm",
        "size": "King Size",
        "backStyle": "Cushioned Back",
        "specialFeature": "Under-seat storage, Convertible to bed",
        "productCareInstructions": "Vacuum regularly. Use fabric cleaner for stains.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "Fabric"
    },
    {
        "id": 5,
        "title": "Austria Sofa With Box Storage (Queen Size, Columbian Walnut Finish)",
        "price": 23989,
        "mrp": 30000,
        "offerPercentage": 20,
        "description": "Queen size sofa cum bed with box storage and Columbian walnut finish, perfect for multifunctional spaces.",
        "category": "sofa bed",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1658989497/crusader/variants/PB-LR0219/Remi-Left-Chaise-sectional-sofa-Square-Set_6-1658989495.jpg",
        "rating": {
            "rate": 4.1,
            "count": 5
        },
        "brand": "Nilkamal",
        "colour": "Columbian Walnut",
        "material": "Engineered Wood",
        "productDimensions": "180D x 140W x 85H cm",
        "size": "Queen Size",
        "backStyle": "Button Tufted Back",
        "specialFeature": "Hidden storage, Convertible",
        "productCareInstructions": "Spot clean with mild detergent. Avoid direct sunlight.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "Fabric"
    },
    {
        "id": 6,
        "title": "Della Sheesham Wood Sofa With Armrests (Honey Irish Cream)",
        "price": 32999,
        "mrp": 40000,
        "offerPercentage": 18,
        "description": "Sheesham wood sofa cum bed with armrests and honey Irish cream finish, offering comfort and style.",
        "category": "sofa bed",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1626926298/crusader/variants/54000027-LE4016/Jonathan-3-Seater-Sofa-Leather-Brown-Lifestyle-Crop.jpg",
        "rating": {
            "rate": 4.4,
            "count": 362
        },
        "brand": "Urban Ladder",
        "colour": "Honey Irish Cream",
        "material": "Sheesham Wood",
        "productDimensions": "190D x 130W x 90H cm",
        "size": "3 Seater",
        "backStyle": "Pillow Back",
        "specialFeature": "Comfortable seating, Modern design",
        "productCareInstructions": "Wipe with a dry cloth. Avoid using abrasive cleaners.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "Fabric"
    },
    {
        "id": 7,
        "title": "Lynet Sheesham Wood Coffee Table with Center (Honey Finish)",
        "price": 14349,
        "mrp": 18000,
        "offerPercentage": 20,
        "description": "Sheesham wood coffee table with center storage and honey finish, practical and elegant for living spaces.",
        "category": "coffee table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1692429849/crusader/variants/40550226/Casa-Round-Coffee-Table-Square-Set_3-1692429847.jpg",
        "rating": {
            "rate": 4.6,
            "count": 843
        },
        "brand": "Pepperfry",
        "colour": "Honey",
        "material": "Sheesham Wood",
        "productDimensions": "100D x 60W x 45H cm",
        "size": "Medium",
        "backStyle": "None",
        "specialFeature": "Storage space, Elegant design",
        "productCareInstructions": "Dust regularly with a dry cloth. Avoid water exposure.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "Wood"
    },
    {
        "id": 8,
        "title": "Uplift Sheesham Wood Coffee Table with Honey Finish",
        "price": 15499,
        "mrp": 20000,
        "offerPercentage": 22,
        "description": "Sheesham wood coffee table with a honey finish, adding a touch of sophistication to your living room.",
        "category": "coffee table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1714374228/crusader/variants/50720021/Sierra-Coffee-Table-Square-Set_1-1714374228.jpg",
        "rating": {
            "rate": 4.2,
            "count": 412
        },
        "brand": "Home Centre",
        "colour": "Honey",
        "material": "Sheesham Wood",
        "productDimensions": "110D x 70W x 46H cm",
        "size": "Large",
        "backStyle": "None",
        "specialFeature": "Contemporary design, Durable finish",
        "productCareInstructions": "Use a soft, dry cloth to clean. Avoid water and chemicals.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "None"
    },
    {
        "id": 9,
        "title": "Aurelia Solid Wood Dining Chair (Mahogany Finish)",
        "price": 8499,
        "mrp": 10000,
        "offerPercentage": 15,
        "description": "Solid wood dining chair with a mahogany finish, featuring a cushioned seat for comfort.",
        "category": "chair",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1716794650/crusader/variants/50850062-WC/Bruno-Side-Table-With-Bruno-Coffee-Table-Square-Set_3-1716794650.jpg",
        "rating": {
            "rate": 4.7,
            "count": 127
        },
        "brand": "HomeTown",
        "colour": "Mahogany",
        "material": "Solid Wood",
        "productDimensions": "45D x 45W x 90H cm",
        "size": "Standard",
        "backStyle": "Slat Back",
        "specialFeature": "Ergonomic design, Cushioned seat",
        "productCareInstructions": "Wipe with a dry cloth. Avoid using water or harsh chemicals.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "Fabric"
    },
    {
        "id": 10,
        "title": "Carvel Compact Study Table (Oak Finish)",
        "price": 12999,
        "mrp": 16000,
        "offerPercentage": 18,
        "description": "Compact study table with an oak finish, perfect for small spaces and minimalistic design.",
        "category": "study table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1698291141/crusader/variants/54000145-NG4001/Dawson-non-storage-bed-Beach-Linen-Square-Set_1-1698291141.jpg",
        "rating": {
            "rate": 4.3,
            "count": 56
        },
        "brand": "Urban Ladder",
        "colour": "Oak",
        "material": "Engineered Wood",
        "productDimensions": "120D x 60W x 75H cm",
        "size": "Compact",
        "backStyle": "None",
        "specialFeature": "Compact design, Easy assembly",
        "productCareInstructions": "Clean with a soft, dry cloth. Avoid moisture.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "None"
    },
    {
        "id": 11,
        "title": "Ariana Solid Wood Bookshelf (Teak Finish)",
        "price": 20499,
        "mrp": 25000,
        "offerPercentage": 18,
        "description": "Solid wood bookshelf with a teak finish, offering ample storage space with a sturdy design.",
        "category": "bookshelf",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1698291141/crusader/variants/54000145-NG4001/Dawson-non-storage-bed-Beach-Linen-Square-Set_1-1698291141.jpg",
        "rating": {
            "rate": 4.5,
            "count": 82
        },
        "brand": "Wooden Street",
        "colour": "Teak",
        "material": "Solid Wood",
        "productDimensions": "180D x 90W x 200H cm",
        "size": "Large",
        "backStyle": "None",
        "specialFeature": "Multiple shelves, High durability",
        "productCareInstructions": "Dust regularly. Avoid exposure to moisture.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "None"
    },
    {
        "id": 12,
        "title": "Adriana Bedside Table (Walnut Finish)",
        "price": 7999,
        "mrp": 10000,
        "offerPercentage": 20,
        "description": "Elegant bedside table with a walnut finish, featuring a drawer and open shelf for storage.",
        "category": "bedside table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1697775257/crusader/variants/PB-001217/Cresent-Bed-With-2-1-Drawer-Nightstand-Square-Set_3-1697775255.jpg",
        "rating": {
            "rate": 4.1,
            "count": 64
        },
        "brand": "IKEA",
        "colour": "Walnut",
        "material": "Engineered Wood",
        "productDimensions": "50D x 40W x 55H cm",
        "size": "Standard",
        "backStyle": "None",
        "specialFeature": "Compact design, Easy assembly",
        "productCareInstructions": "Wipe with a dry cloth. Avoid exposure to water.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "None"
    },
    {
        "id": 13,
        "title": "Xander Solid Wood Study Desk (Honey Finish)",
        "price": 16999,
        "mrp": 21000,
        "offerPercentage": 19,
        "description": "Solid wood study desk with a honey finish, offering a spacious workspace and drawers for storage.",
        "category": "study table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1666680652/crusader/variants/PB-BR0202/Seb-Bed-With-2-Side-Tables-With-4-Drawer-Dresser-Set-1666680650.jpg",
        "rating": {
            "rate": 4.6,
            "count": 74
        },
        "brand": "HomeTown",
        "colour": "Honey",
        "material": "Solid Wood",
        "productDimensions": "140D x 70W x 75H cm",
        "size": "Large",
        "backStyle": "None",
        "specialFeature": "Spacious design, Sturdy construction",
        "productCareInstructions": "Wipe with a soft, dry cloth. Avoid moisture and chemicals.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "None"
    },
    {
        "id": 14,
        "title": "Caldero Solid Wood Coffee Table (Teak Finish)",
        "price": 11999,
        "mrp": 15000,
        "offerPercentage": 20,
        "description": "Solid wood coffee table with a teak finish, featuring a lower shelf for additional storage.",
        "category": "coffee table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1693795800/crusader/variants/50440835-NG4001/Dalton-Storage-Bed-With-Harper-Side-Table-Square-Set_1-1693795799.jpg",
        "rating": {
            "rate": 4.4,
            "count": 134
        },
        "brand": "Wooden Street",
        "colour": "Teak",
        "material": "Solid Wood",
        "productDimensions": "100D x 60W x 45H cm",
        "size": "Medium",
        "backStyle": "None",
        "specialFeature": "Lower shelf, Durable design",
        "productCareInstructions": "Dust regularly with a dry cloth. Avoid exposure to water.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "None"
    },
    {
        "id": 15,
        "title": "Harley Recliner Sofa (Brown Leather)",
        "price": 75999,
        "mrp": 90000,
        "offerPercentage": 16,
        "description": "Luxurious recliner sofa in brown leather, offering supreme comfort and style for your living room.",
        "category": "sofa",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1663669003/crusader/variants/40550199/Emery-Bed-Square-Set_5-1663669000.jpg",
        "rating": {
            "rate": 4.8,
            "count": 56
        },
        "brand": "Nilkamal",
        "colour": "Brown",
        "material": "Leather",
        "productDimensions": "220D x 100W x 90H cm",
        "size": "3 Seater",
        "backStyle": "Cushioned Back",
        "specialFeature": "Reclining feature, High-quality leather",
        "productCareInstructions": "Wipe with a damp cloth. Avoid direct sunlight and chemicals.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "Leather"
    },
    {
        "id": 16,
        "title": "Zenith Glass Top Dining Table (6 Seater, Black)",
        "price": 38999,
        "mrp": 48000,
        "offerPercentage": 19,
        "description": "Elegant glass top dining table with a black frame, comfortably seating up to 6 people. Ideal for modern dining rooms.",
        "category": "dining table",
        "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1692349090/crusader/variants/40550220/Casa-TV-Console-Square-Set_1-1692349088.jpg",
        "rating": {
            "rate": 4.6,
            "count": 99
        },
        "brand": "Furny",
        "colour": "Black",
        "material": "Glass and Metal",
        "productDimensions": "160D x 90W x 75H cm",
        "size": "6 Seater",
        "backStyle": "None",
        "specialFeature": "Glass top, Modern design",
        "productCareInstructions": "Clean with a glass cleaner. Wipe metal parts with a dry cloth.",
        "netQuantity": "1 Piece",
        "seatMaterialType": "None"
    },
    
        {
            "id": 17,
            "title": "Orchid Recliner Chair",
            "price": 24999,
            "mrp": 32000,
            "offerPercentage": 22,
            "description": "Comfortable recliner chair with adjustable backrest, perfect for relaxing after a long day.",
            "category": "recliner",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1713425275/crusader/variants/AS-000465/Seb-TV-Storage-Large-System-Suqare-Set_1-1713425272.jpg",
            "rating": {
                "rate": 4.7,
                "count": 65
            },
            "brand": "ComfortZone",
            "colour": "Grey",
            "material": "Fabric",
            "productDimensions": "85D x 80W x 100H cm",
            "size": "Standard",
            "backStyle": "Reclining",
            "specialFeature": "Adjustable backrest, Ergonomic design",
            "productCareInstructions": "Vacuum regularly. Spot clean with a mild detergent.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "Fabric"
        },
        {
            "id": 18,
            "title": "Luxe Leather Office Chair",
            "price": 12999,
            "mrp": 16000,
            "offerPercentage": 19,
            "description": "Luxurious leather office chair with adjustable height and tilt, providing comfort for long hours at work.",
            "category": "office chair",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1692345583/crusader/variants/40550217/Casa-Sideboard-Square-Set_1-1692345581.jpg",
            "rating": {
                "rate": 4.8,
                "count": 120
            },
            "brand": "OfficeMate",
            "colour": "Black",
            "material": "Leather",
            "productDimensions": "60D x 60W x 110H cm",
            "size": "Adjustable",
            "backStyle": "High back",
            "specialFeature": "Adjustable height, Tilt mechanism",
            "productCareInstructions": "Wipe with a damp cloth. Avoid harsh chemicals.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "Leather"
        },
        {
            "id": 19,
            "title": "Classic Wooden Coffee Table",
            "price": 15999,
            "mrp": 20000,
            "offerPercentage": 20,
            "description": "Timeless wooden coffee table with a classic design, ideal for any living room setting.",
            "category": "coffee table",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1641890653/crusader/variants/50850026-WA/Luka-Cabinate-Square-Set_1.jpg",
            "rating": {
                "rate": 4.5,
                "count": 80
            },
            "brand": "WoodWorks",
            "colour": "Brown",
            "material": "Wood",
            "productDimensions": "100D x 60W x 45H cm",
            "size": "Medium",
            "backStyle": "N/A",
            "specialFeature": "Classic design, Sturdy construction",
            "productCareInstructions": "Dust regularly. Use wood polish for shine.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
        {
            "id": 20,
            "title": "Modern Glass Cabinet",
            "price": 34999,
            "mrp": 45000,
            "offerPercentage": 22,
            "description": "Sleek glass cabinet with ample storage space, perfect for displaying and organizing your items.",
            "category": "cabinet",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1697772401/crusader/variants/40280044/Crescent-6-Drawer-Dresser-Square-Set_1-1697772399.jpg",
            "rating": {
                "rate": 4.6,
                "count": 90
            },
            "brand": "DesignMasters",
            "colour": "Clear",
            "material": "Glass and Wood",
            "productDimensions": "120D x 40W x 180H cm",
            "size": "Large",
            "backStyle": "Closed",
            "specialFeature": "Glass shelves, Modern design",
            "productCareInstructions": "Clean with glass cleaner. Wipe wood parts with a dry cloth.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
        {
            "id": 21,
            "title": "Elegant Dining Chairs (Set of 4)",
            "price": 19999,
            "mrp": 25000,
            "offerPercentage": 20,
            "description": "Set of 4 elegant dining chairs with a plush cushion for comfort, perfect for any dining area.",
            "category": "dining chairs",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1626938908/crusader/variants/52460075/Esther-Bookshelf-Tall-Lifestyle-Crop.jpg",
            "rating": {
                "rate": 4.4,
                "count": 70
            },
            "brand": "Elegance",
            "colour": "Beige",
            "material": "Fabric and Wood",
            "productDimensions": "50D x 45W x 95H cm",
            "size": "Standard",
            "backStyle": "High back",
            "specialFeature": "Plush cushion, Sturdy construction",
            "productCareInstructions": "Vacuum regularly. Spot clean stains.",
            "netQuantity": "4 Pieces",
            "seatMaterialType": "Fabric"
        },
        {
            "id": 22,
            "title": "Contemporary TV Stand",
            "price": 25999,
            "mrp": 32000,
            "offerPercentage": 19,
            "description": "Modern TV stand with ample storage space and a sleek design to complement your living room.",
            "category": "TV stand",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1684491338/crusader/variants/50520007/Sloane-Shelf-Square-Set_2-1684491331.jpg",
            "rating": {
                "rate": 4.7,
                "count": 110
            },
            "brand": "ModernLiving",
            "colour": "White",
            "material": "Wood and Metal",
            "productDimensions": "150D x 40W x 60H cm",
            "size": "Medium",
            "backStyle": "Open",
            "specialFeature": "Ample storage, Modern design",
            "productCareInstructions": "Dust regularly. Wipe with a damp cloth.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
        {
            "id": 23,
            "title": "Rustic Bedside Table",
            "price": 8999,
            "mrp": 12000,
            "offerPercentage": 25,
            "description": "Charming rustic bedside table with a single drawer and shelf, perfect for adding character to your bedroom.",
            "category": "bedside table",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1679036144/crusader/variants/50440807-TD4002/Colette-Swivel-Armchair-Teddy-Brown-Square-Set_4-1679036142.jpg",
            "rating": {
                "rate": 4.5,
                "count": 50
            },
            "brand": "RusticCharm",
            "colour": "Natural Wood",
            "material": "Wood",
            "productDimensions": "45D x 40W x 60H cm",
            "size": "Small",
            "backStyle": "Closed",
            "specialFeature": "Rustic design, Ample storage",
            "productCareInstructions": "Dust regularly. Use wood polish for shine.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
        {
            "id": 24,
            "title": "Industrial Bar Stool",
            "price": 7499,
            "mrp": 10000,
            "offerPercentage": 25,
            "description": "Stylish industrial bar stool with adjustable height and metal frame, suitable for modern bars and kitchens.",
            "category": "bar stool",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1707192822/crusader/variants/PB-001333-BW4002/Desmond-Armchair-With-Ottoman-Opal-Beige-Square-Set_1-1707192816.jpg",
            "rating": {
                "rate": 4.4,
                "count": 45
            },
            "brand": "UrbanStyle",
            "colour": "Black",
            "material": "Metal and Leather",
            "productDimensions": "40D x 40W x 75-90H cm",
            "size": "Adjustable",
            "backStyle": "Low back",
            "specialFeature": "Adjustable height, Industrial design",
            "productCareInstructions": "Wipe with a damp cloth. Avoid excessive moisture.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "Leather"
        },
        {
            "id": 25,
            "title": "Scandinavian Bookcase",
            "price": 29999,
            "mrp": 38000,
            "offerPercentage": 21,
            "description": "Elegant Scandinavian bookcase with multiple shelves for ample storage and display options.",
            "category": "bookcase",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1663208722/crusader/variants/40550204/Seb-Chair-Dark-Graphite-Square-Set_1-1663208719.jpg",
            "rating": {
                "rate": 4.6,
                "count": 85
            },
            "brand": "NordicDesign",
            "colour": "White and Wood",
            "material": "Wood",
            "productDimensions": "120D x 30W x 180H cm",
            "size": "Large",
            "backStyle": "Open",
            "specialFeature": "Scandinavian design, Multiple shelves",
            "productCareInstructions": "Dust regularly. Wipe with a damp cloth.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
        {
            "id": 26,
            "title": "Minimalist Writing Desk",
            "price": 14999,
            "mrp": 19000,
            "offerPercentage": 21,
            "description": "Sleek minimalist writing desk with a spacious work surface and clean lines, ideal for home offices.",
            "category": "writing desk",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1713428896/crusader/variants/50320003-TL4002/Thierry-Chair-Pearl-Beige-Square-Set_2-1713428896.jpg",
            "rating": {
                "rate": 4.3,
                "count": 70
            },
            "brand": "SimpleLiving",
            "colour": "Black",
            "material": "Wood",
            "productDimensions": "120D x 60W x 75H cm",
            "size": "Medium",
            "backStyle": "Open",
            "specialFeature": "Minimalist design, Spacious surface",
            "productCareInstructions": "Dust regularly. Wipe with a damp cloth.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
        {
            "id": 27,
            "title": "Vintage Storage Bench",
            "price": 11999,
            "mrp": 15000,
            "offerPercentage": 20,
            "description": "Charming vintage storage bench with padded cushion and ample storage space for your essentials.",
            "category": "storage bench",
            "image":"https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1713947237/crusader/variants/50320005-IN4002/Simone-Chair-Performance-White-Quartz-Boucle-Square-Set_2-1713947237.jpg",
            "rating": {
                "rate": 4.6,
                "count": 60
            },
            "brand": "VintageFinds",
            "colour": "Beige",
            "material": "Fabric and Wood",
            "productDimensions": "120D x 40W x 50H cm",
            "size": "Large",
            "backStyle": "Closed",
            "specialFeature": "Padded cushion, Storage compartment",
            "productCareInstructions": "Vacuum regularly. Spot clean stains.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "Fabric"
        },
        {
            "id": 28,
            "title": "Elegant Console Table",
            "price": 13999,
            "mrp": 18000,
            "offerPercentage": 22,
            "description": "Sophisticated console table with a sleek design and elegant finish, perfect for entryways and hallways.",
            "category": "console table",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1655434106/crusader/variants/54000059-LE4016/Abel-Counter-Stool-Caramel-Det_1-1655434104.jpg",
            "rating": {
                "rate": 4.5,
                "count": 55
            },
            "brand": "Elegance",
            "colour": "White",
            "material": "Wood",
            "productDimensions": "90D x 35W x 75H cm",
            "size": "Medium",
            "backStyle": "Open",
            "specialFeature": "Sleek design, Elegant finish",
            "productCareInstructions": "Dust regularly. Wipe with a damp cloth.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
        {
            "id": 29,
            "title": "Boho Wall Shelf Set",
            "price": 8999,
            "mrp": 11000,
            "offerPercentage": 18,
            "description": "Set of 3 boho-style wall shelves for decorative and storage purposes, adding a stylish touch to your walls.",
            "category": "wall shelf",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1715911638/crusader/variants/50720027-LD4001/Sorrento-Outdoor-2-Chaises-Lounge-Light-Grey-Square-Set_2-1715911636.jpg",
            "rating": {
                "rate": 4.3,
                "count": 45
            },
            "brand": "BohoDecor",
            "colour": "Natural Wood",
            "material": "Wood",
            "productDimensions": "Various sizes",
            "size": "Set of 3",
            "backStyle": "Open",
            "specialFeature": "Boho design, Easy to install",
            "productCareInstructions": "Dust regularly. Wipe with a damp cloth.",
            "netQuantity": "3 Pieces",
            "seatMaterialType": "N/A"
        },
        {
            "id": 30,
            "title": "Retro Armchair",
            "price": 19999,
            "mrp": 25000,
            "offerPercentage": 20,
            "description": "Vintage-inspired armchair with comfortable cushioning and a retro design, ideal for cozy living spaces.",
            "category": "armchair",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1717473790/crusader/variants/44230015/Mira-Rug-Square-Set_1-1717473789.jpg",

            "rating": {
                "rate": 4.4,
                "count": 70
            },
            "brand": "RetroHome",
            "colour": "Green",
            "material": "Fabric",
            "productDimensions": "80D x 70W x 85H cm",
            "size": "Standard",
            "backStyle": "High back",
            "specialFeature": "Vintage design, Comfortable cushioning",
            "productCareInstructions": "Vacuum regularly. Spot clean stains.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "Fabric"
        },
        {
            "id": 31,
            "title": "Luxurious Bed Frame",
            "price": 49999,
            "mrp": 60000,
            "offerPercentage": 17,
            "description": "Opulent bed frame with an elegant design and high-quality materials, providing a touch of luxury to your bedroom.",
            "category": "bed frame",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1717472811/crusader/variants/44230036/Atmore-Area-Rug-Square-Set_1-1717472811.jpg",

            "rating": {
                "rate": 4.8,
                "count": 90
            },
            "brand": "LuxuryLiving",
            "colour": "Champagne",
            "material": "Wood and Fabric",
            "productDimensions": "200D x 180W x 100H cm",
            "size": "King Size",
            "backStyle": "High headboard",
            "specialFeature": "Elegant design, High-quality materials",
            "productCareInstructions": "Dust regularly. Use upholstery cleaner for stains.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
        {
            "id": 32,
            "title": "Contemporary Dining Table Set (4 Seater)",
            "price": 27999,
            "mrp": 35000,
            "offerPercentage": 20,
            "description": "Modern dining table set with a sleek design, including 4 comfortable chairs, perfect for contemporary dining rooms.",
            "category": "dining table set",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1637830708/crusader/variants/40370038/Ventura-Jute-Rug-Natural-Black-Square-Set_1.jpg",
            "rating": {
                "rate": 4.6,
                "count": 80
            },
            "brand": "Contempo",
            "colour": "Gray",
            "material": "Wood and Fabric",
            "productDimensions": "Table: 120D x 80W x 75H cm; Chairs: 45D x 45W x 90H cm",
            "size": "4 Seater",
            "backStyle": "High back",
            "specialFeature": "Sleek design, Comfortable chairs",
            "productCareInstructions": "Dust regularly. Wipe with a damp cloth.",
            "netQuantity": "1 Table + 4 Chairs",
            "seatMaterialType": "Fabric"
        },
        {
            "id": 33,
            "title": "Industrial Coffee Table",
            "price": 14999,
            "mrp": 19000,
            "offerPercentage": 21,
            "description": "Industrial-style coffee table with a metal frame and wooden top, offering a rugged and stylish look.",
            "category": "coffee table",
            "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1716345142/crusader/variants/50630009/Luna-Floor-Mirror-Square-Set_1_-1716345140.jpg",
            "rating": {
                "rate": 4.5,
                "count": 65
            },
            "brand": "UrbanWorks",
            "colour": "Black and Wood",
            "material": "Metal and Wood",
            "productDimensions": "100D x 60W x 45H cm",
            "size": "Medium",
            "backStyle": "N/A",
            "specialFeature": "Industrial design, Sturdy construction",
            "productCareInstructions": "Wipe with a damp cloth. Avoid excessive moisture.",
            "netQuantity": "1 Piece",
            "seatMaterialType": "N/A"
        },
            {
                "id": 34,
                "title": "Crimson Wall Mirror with Modern Flair Accessorie (Wall Mirrors)",
                "price": 349,
                "mrp": 450,
                "offerPercentage": 22,
                "description": "A modern Crimson wall mirror that adds a stylish flair to your living space.",
                "category": "Wall Mirrors",
                "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1715927340/crusader/variants/50630015/Crimson-Wall-Mirror-Square-Set_1-1715927338.jpg",
                "rating": {
                    "rate": 4.4,
                    "count": 25
                },
                "brand": "UrbanWorks",
                "colour": "Black and Wood",
                "material": "Metal and Wood",
                "productDimensions": "100D x 60W x 45H cm",
                "size": "Medium",
                "backStyle": "N/A",
                "specialFeature": "Industrial design, Sturdy construction",
                "productCareInstructions": "Wipe with a damp cloth. Avoid excessive moisture.",
                "netQuantity": "1 Piece",
                "seatMaterialType": "N/A"
            },
            {
                "id": 35,
                "title": "Alba Fluted Ceramic Table Lamp Accessorie (LightLamps)",
                "price": 179,
                "mrp": 250,
                "offerPercentage": 28,
                "description": "A stylish Alba fluted ceramic table lamp that brings a touch of elegance and warmth to any room.",
                "category": "LightLamps",
                "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1715911845/crusader/variants/50230042/Alba-Fluted-Ceramic-Table-Lamp-Square-Set_1-1715911842.jpg",
                "rating": {
                    "rate": 4.3,
                    "count": 20
                },
                "brand": "UrbanWorks",
                "colour": "Black and Wood",
                "material": "Metal and Wood",
                "productDimensions": "100D x 60W x 45H cm",
                "size": "Medium",
                "backStyle": "N/A",
                "specialFeature": "Industrial design, Sturdy construction",
                "productCareInstructions": "Wipe with a damp cloth. Avoid excessive moisture.",
                "netQuantity": "1 Piece",
                "seatMaterialType": "N/A"
            },
            {
                "id": 36,
                "title": "Cedric Floor Lamp with Contemporary Design Accessorie (LightLamps)",
                "price": 299,
                "mrp": 400,
                "offerPercentage": 25,
                "description": "The Cedric floor lamp features a contemporary design, perfect for adding modern lighting to your home.",
                "category": "LightLamps",
                "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1715068043/crusader/variants/50230010/Cedric-Floor-Lamp-Suqare-Set_1-1715068042.jpg",
                "rating": {
                    "rate": 4.4,
                    "count": 15
                },
                "brand": "UrbanWorks",
                "colour": "Black and Wood",
                "material": "Metal and Wood",
                "productDimensions": "100D x 60W x 45H cm",
                "size": "Medium",
                "backStyle": "N/A",
                "specialFeature": "Industrial design, Sturdy construction",
                "productCareInstructions": "Wipe with a damp cloth. Avoid excessive moisture.",
                "netQuantity": "1 Piece",
                "seatMaterialType": "N/A"
            },
            {
                "id": 37,
                "title": "Karo Tripod Floor Lamp in Caramel Accessorie (LightLamps)",
                "price": 249,
                "mrp": 350,
                "offerPercentage": 29,
                "description": "A Karo tripod floor lamp in caramel, combining style and functionality to illuminate your space.",
                "category": "LightLamps",
                "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1715067585/crusader/variants/50230028/Karo-Tripod-Floor-Lamp-Caramel-Square-Set_1-1715067585.jpg",
                "rating": {
                    "rate": 4.5,
                    "count": 22
                },
                "brand": "UrbanWorks",
                "colour": "Black and Wood",
                "material": "Metal and Wood",
                "productDimensions": "100D x 60W x 45H cm",
                "size": "Medium",
                "backStyle": "N/A",
                "specialFeature": "Industrial design, Sturdy construction",
                "productCareInstructions": "Wipe with a damp cloth. Avoid excessive moisture.",
                "netQuantity": "1 Piece",
                "seatMaterialType": "N/A"
            },
            {
                "id": 38,
                "title": "Cedric Table Lamp with Sleek Design Accessorie",
                "price": 129,
                "mrp": 180,
                "offerPercentage": 28,
                "description": "The Cedric table lamp features a sleek design, perfect for adding a touch of modern elegance to any room.",
                "category": "Table Lamps",
                "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1697773910/crusader/variants/PB-001137/Cedric-Table-Lamp-Square-Set_2-1697773908.jpg",
                "rating": {
                    "rate": 4.4,
                    "count": 22
                },
                "brand": "UrbanWorks",
                "colour": "Black and Wood",
                "material": "Metal and Wood",
                "productDimensions": "100D x 60W x 45H cm",
                "size": "Medium",
                "backStyle": "N/A",
                "specialFeature": "Industrial design, Sturdy construction",
                "productCareInstructions": "Wipe with a damp cloth. Avoid excessive moisture.",
                "netQuantity": "1 Piece",
                "seatMaterialType": "N/A"
            },
            {
                "id": 39,
                "title": "Burgeon Marble Table Lamp with Classic Charm Accessorie",
                "price": 149,
                "mrp": 200,
                "offerPercentage": 25,
                "description": "The Burgeon marble table lamp adds classic charm and sophistication to your home decor.",
                "category": "Table Lamps",
                "image": "https://res.cloudinary.com/castlery/image/private/w_400,f_auto,q_auto/b_rgb:FFFFFF,c_fit/v1698290419/crusader/variants/PB-001268/Burgeon-Marble-Table-Lamp-Square-Set_2-1698290419.jpg",
                "rating": {
                    "rate": 4.6,
                    "count": 18
                },
                "brand": "UrbanWorks",
                "colour": "Black and Wood",
                "material": "Metal and Wood",
                "productDimensions": "100D x 60W x 45H cm",
                "size": "Medium",
                "backStyle": "N/A",
                "specialFeature": "Industrial design, Sturdy construction",
                "productCareInstructions": "Wipe with a damp cloth. Avoid excessive moisture.",
                "netQuantity": "1 Piece",
                "seatMaterialType": "N/A"
            }
        ]
        